
- name: Install Redis dependencies
  apt:
    name: '{{ item }}'
    state: latest
  loop:
    - build-essential
    - tcl
  tags:
    - deps
    - deps-redis

- name: Download Redis stable release
  unarchive:
    src: http://download.redis.io/redis-stable.tar.gz
    dest: /tmp/
    remote_src: true

- name: Install Redis
  command: chdir=/tmp/redis-stable {{ item }}
  loop:
    - make
    - make test
    - make install

