
- name: Check if vtop is installed
  command: bash -c '{{ nvm_source }} && vtop -V'
  register: vtop_installed
  ignore_errors: true
  tags:
    - check
    - check-vtop
    - always

- name: Install vtop
  shell: bash -c '{{ nvm_source }} && npm install -g vtop'
  become_user: '{{ ansible_user_id }}'
  when: vtop_installed.rc != 0
