- name: Gather Facts
  gather_facts: yes
  hosts: local

- name: Setup dotfiles
  gather_facts: no
  hosts: local
  user: '{{ ansible_user_id }}'
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - role: base
      tags:
        - base
    - role: git
      tags:
        - git
    - role: interface
      tags:
        - interface
    - role: fonts
      tags:
        - fonts
    - role: zsh
      tags:
        - zsh
    - role: fzf
      tags:
        - fzf
    - role: ag
      tags:
        - ag
    - role: gron
      tags:
        - gron
    - role: resty
      tags:
        - resty
    - role: nvm
      tags:
        - nvm
    - role: pyenv
      tags:
        - pyenv
    - role: tmux
      tags:
        - tmux
    - role: termite
      tags:
        - termite
    - role: vscode
      tags:
        - vscode
    - role: docker
      tags:
        - docker
    - role: elasticsearch
      tags:
        - elasticsearch
    - role: redis
      tags:
        - redis
    - role: psql
      tags:
        - psql
    - role: spotify
      tags:
        - spotify
    - role: vlc
      tags:
        - vlc
    - role: heroku
      tags:
        - heroku
    - role: transmission
      tags:
        - transmission
    - role: gimp
      tags:
       - gimp
    - role: libreoffice
      tags:
       - libreoffice
    - role: wallpapers
      tags:
        - wallpapers
    - role: numix
      tags:
        - numix
    - role: adapta
      tags:
        - adapta
    - role: finish
      tags:
        - finish
