
- block:
  - name: Check if vscode is installed
    command: code -v
    become_user: '{{ ansible_user_id }}'
    ignore_errors: true
    register: code_installed
    tags:
      - check
      - check-vscode

  - name: Download and install vscode
    apt:
      deb: https://go.microsoft.com/fwlink/?LinkID=760868
      state: present
    when: code_installed.rc != 0

  - name: Install code-settings-sync extension
    command: code --install-extension Shan.code-settings-sync
    become_user: '{{ ansible_user_id }}'

    tags:
      - files
      - files-vscode

  tags:
    - install
    - install-vscode
