

- name: Install Fira Code font
  apt:
    name: fonts-firacode
    state: latest

- name: Check if Powerline fonts is installed
  command: apt-cache search font | grep fonts-powerline
  register: powerline_installed
  ignore_errors: yes

- name: Clone Powerline fonts
  git:
    repo: https://github.com/powerline/fonts.git
    depth: 1
    dest: /tmp/powerline-fonts
  when: powerline_installed.rc == 1

- name: Install Powerline fonts
  command: chdir=/tmp/powerline-fonts ./install.sh
  become: yes
  become_user: '{{ ansible_user_id }}'
  when: powerline_installed.rc == 1

- name: Remove Powerline fonts temp files
  file:
    path: /tmp/powerline-fonts
    state: absent
  when: powerline_installed.rc == 1
