
- name: Update and upgrade installed packages
  apt:
    update_cache: yes
    upgrade: yes
    force_apt_get: true

- name: Install base packages
  apt:
    name: '{{ item }}'
    state: latest
  loop:
    - vim
    - python
    - python-minimal
    - python-dev
    - python-pip
    - python3
    - python3-dev
    - python3-pip
    - python3-venv

- name: Move button layout to left
  gsettings:
    key: org.gnome.desktop.wm.preferences.button-layout
    value: "'close,maximize,minimize:'"
    state: present
    user: '{{ ansible_user_id }}'

- name: Configure launcher favorites
  gsettings:
    key: org.gnome.shell.favorite-apps
    value: "{{ lookup('file', 'favorite-apps.txt') }}"
    state: present
    user: '{{ ansible_user_id }}'

- name: Configure Dash-To-Dock
  gsettings:
    key: '{{ item }}'
    value: "false"
    state: present
    user: '{{ ansible_user_id }}'
  loop:
    - org.gnome.shell.extensions.dash-to-dock.dock-fixed
    - org.gnome.shell.extensions.dash-to-dock.custom-theme-customize-running-dots

- import_tasks: fonts.yml
