
- name: Check if zsh is installed
  command: zsh --version
  register: zsh_installed
  ignore_errors: true
  tags:
    - check
    - check-zsh
    - always

- block:
  - import_tasks: install.yml
    when: zsh_version not in zsh_installed.stdout

  - import_tasks: extensions/oh-my-zsh.yml
    tags:
      - install-oh-my-zsh

  - import_tasks: extensions/guri.yml
    tags:
      - install-guri

  - import_tasks: extensions/zsh-syntax-highlighting.yml
    tags:
      - install-zsh-syntax-highlightning

  - name: Copy .zshrc
    copy:
      src: .zshrc
      dest: "{{ ansible_env.HOME }}/.zshrc"
      owner: "{{ ansible_user_id }}"
    tags:
     - files
     - files-zsh

  tags:
    - install
    - install-zsh
