
- name: Move button layout to left
  gsettings:
    key: org.gnome.desktop.wm.preferences.button-layout
    value: "'close,maximize,minimize:'"
    state: present
    user: '{{ ansible_user_id }}'

- name: Configure launcher favorites
  gsettings:
    key: org.gnome.shell.favorite-apps
    value: "{{ lookup('file', 'favorite-apps.txt') }}"
    state: present
    user: '{{ ansible_user_id }}'

- name: Configure Dash-To-Dock
  gsettings:
    key: '{{ item }}'
    value: "false"
    state: present
    user: '{{ ansible_user_id }}'
  loop:
    - org.gnome.shell.extensions.dash-to-dock.dock-fixed
    - org.gnome.shell.extensions.dash-to-dock.custom-theme-customize-running-dots
