
- name: Check if panel-osd is installed
  command: gsettings list-keys org.gnome.shell.extensions.panel-osd
  register: panel_osd_installed
  become_user: '{{ ansible_user_id }}'
  ignore_errors: true

- name: Clone panel-osd
  git:
    repo: https://github.com/jenslody/gnome-shell-extension-panel-osd.git
    dest: /tmp/panel-osd
  when: panel_osd_installed.rc != 0

- name: Install panel-osd Gnome Extension
  command: chdir=/tmp/panel-osd {{ item }}
  loop:
    - ./autogen.sh
    - make
    - make install
  when: panel_osd_installed.rc != 0

- name: Remove /tmp/panel-osd
  file:
    path: /tmp/panel-osd
    state: absent
  when: panel_osd_installed.rc != 0

- name: Move Notifications Panel to top-right
  gsettings:
    key: org.gnome.shell.extensions.panel-osd.{{ item }}
    value: 100.0
    user: '{{ ansible_user_id }}'
  loop:
    - x-pos
    - y-pos
