
- name: Install Termite's dependencies
  apt:
    name: '{{ item }}'
    state: latest
  loop:
    - g++
    - libgtk-3-dev
    - gtk-doc-tools
    - gnutls-bin
    - valac
    - intltool
    - libpcre2-dev
    - libglib3.0-cil-dev
    - libgnutls28-dev
    - libgirepository1.0-dev
    - libxml2-utils
    - gperf
  tags:
    - deps
    - deps-termite

- import_tasks: vte-ng.yml
  tags:
    - install-vte-ng

- name: Clone Termite's repository
  git:
    repo: https://github.com/thestinger/termite.git
    recursive: yes
    dest: /tmp/termite

- name: Install Termite
  command: chdir=/tmp/termite {{ item }}
  loop:
    - make
    - make install
    - ldconfig

- name: Update alternatives
  alternatives:
    link: /usr/bin/x-terminal-emulator
    name: x-terminal-emulator
    path: /usr/local/bin/termite-tmux
    priority: 60

- name: Remove gnome-terminal
  apt:
    name: gnome-terminal
    state: absent
    purge: yes
    autoclean: yes
    autoremove: yes

- name: Remove /tmp/termite
  file:
    path: /tmp/termite
    state: absent
