
- block:

  - name: Check if Termite is installed
    command: termite --version
    register: termite_installed
    ignore_errors: yes
    tags:
      - check
      - check-termite

  - block:
    - name: Create ~/.config/termite folder
      file:
        path: '{{ ansible_env.HOME }}/.config/termite'
        state: directory
      tags:
        - files
        - files-termite

    - name: Copy Termite's config file
      copy:
        src: 'config.ini'
        dest: '{{ ansible_env.HOME }}/.config/termite/config'
        owner: '{{ ansible_user_id }}'

    tags:
      - files
      - files-termite

  - import_tasks: install.yml
    when: termite_installed.rc != 0

  - block:
    - name: Create /lib/terminfo/x directory
      file:
        path: /lib/terminfo/x
        state: directory

    - name: Link xterm-termite to /lib/terminfo/x
      file:
        src: /usr/local/share/terminfo/x/xterm-termite
        dest: /lib/terminfo/x/xterm-termite
        state: link

    - name: Copy termite-tmux script
      copy:
        src: termite-tmux
        dest: /usr/local/bin/termite-tmux
        owner: '{{ ansible_user_id }}'
        mode: u+x

    - name: Copy termite.desktop
      copy:
        src: termite.desktop
        dest: '{{ ansible_env.HOME }}/.local/share/applications/termite.desktop'
        owner: '{{ ansible_user_id }}'

    - name: Link termite-tmux to gnome-terminal
      file:
        src: /usr/local/bin/termite-tmux
        dest: /usr/bin/gnome-terminal
        state: link
        remote_src: yes

    tags:
      - files
      - files-termite

  tags:
    - install
    - install-termite
