
- block:
  - name: Check if Spotify is installed
    command: snap list spotify
    register: spotify_installed
    ignore_errors: true
    tags:
      - check
      - check-spotify

  - name: Install Spotify
    command: snap install spotify
    when: spotify_installed.rc != 0

  - name: Update Spotify
    command: snap refresh spotify
    when: spotify_installed.rc == 0

  - name: Copy spotify.desktop
    copy:
      src: spotify.desktop
      dest: '{{ ansible_env.HOME }}/.local/share/applications/spotify.desktop'
      owner: '{{ ansible_user_id }}'
    tags:
      - files
      - files-spotify

  tags:
    - install
    - install-spotify
