
- block:
  - name: Clone fzf
    git:
      repo: https://github.com/junegunn/fzf.git
      dest:  '{{ ansible_env.HOME }}/.fzf'
      depth: 1

  - name: Install fzf
    shell: chdir='' yes | {{ ansible_env.HOME }}/.fzf/install

  tags:
    - install
    - install-fzf
