
- name: Add Adapta's ppa
  apt_repository:
    repo: 'ppa:tista/adapta'
    codename: bionic

- name: Install Adapta Theme
  apt:
    name: adapta-gtk-theme
    state: latest

- name: Set Adapta Theme as default
  gsettings:
    key: '{{ item }}'
    value: "'Adapta-Nokto-Eta'"
    state: present
    user: '{{ ansible_user_id }}'
  loop:
    - org.gnome.desktop.interface.gtk-theme
    - org.gnome.shell.extensions.user-theme.name
