
- name: Install git
  apt:
    name: git
    state: latest
  tags:
    - install
    - install-git

- name: Copy .gitconfig
  template:
    src: gitconfig.j2
    dest: '{{ ansible_env.HOME }}/.gitconfig'
    owner: '{{ ansible_user_id }}'
  tags:
    - files
    - files-git
