
- name: Create ~/.resty
  file:
    path: '{{ ansible_env.HOME }}/.resty'
    state: directory
    owner: '{{ ansible_user_id }}'

- name: Download and install Resty
  get_url:
    url: '{{ resty_url }}'
    dest: '{{ ansible_env.HOME }}/.resty/resty'
    owner: '{{ ansible_user_id }}'
