
- block:
  - name: Check if Heroku is installed
    command: heroku -v
    register: heroku_installed
    ignore_errors: true
    tags:
      - check
      - check-heroku

  - name: Download Heroku
    get_url:
      url: https://cli-assets.heroku.com/install-ubuntu.sh
      dest: /tmp/install-heroku.sh
      owner: '{{ ansible_user_id }}'
    when: heroku_installed.rc != 0

  - name: Install Heroku
    script: /tmp/install-heroku.sh
    when: heroku_installed.rc != 0

  tags:
    - install
    - install-heroku
