
- block:

  - name: Update and upgrade installed packages
    apt:
      update_cache: yes
      upgrade: yes

  - name: Install base packages
    apt:
      name: '{{ item }}'
      state: latest
    loop:
      - vim
      - zip
      - curl
      - wget
      - xclip
      - aptitude
      - python
      - python-minimal
      - python-dev
      - python-pip
      - python3
      - python3-dev
      - python3-pip
      - python3-venv
      - libxml2-dev
      - libncurses5-dev
    tags:
      - install-deps
      - install-deps-base

  - name: Copy .bashrc
    copy:
      src: .bashrc
      dest: '{{ ansible_env.HOME }}/.bashrc'
      owner: '{{ ansible_user_id }}'
    tags:
      - files
      - files-git

  tags:
    - install
    - install-base
