
- name: Clone oh-my-zsh
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh"

- name: Copy .zshrc
  copy:
    src: .zshrc
    dest: "{{ ansible_env.HOME }}/.zshrc"
